### ISSUE TITLE
Building a manga site scraper (A personel request)

### ISSUE THREAD

**Issue by rpdinkar** [sekiju/kindle-manga#2]
Hello, would it be possible to develop a scraper for a specific manga site, which can directly scrape manga series/chapters and upload them on site automatically, i wasn't able to pull request so i wrote here and how can i contact you.

**Comment by knst0** [comment]
If you have Telegram, you can contact me: [ @milczenie ](https://t.me/milczenie)
Discord: Yukije#7714
Or e-mail: sekijudev@gmail.com
